[project]
name = "Clean email and phone from text"
version = "0.1.0"
description = "Remove email addresses and phone numbers from genealogy records"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "5.4.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[pypi-dependencies]
scrubadub = ">=2.0.1, <3"

[feature.dev.dependencies]

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }
